"""empty message

Revision ID: 1ad7254baf97
Revises: 5473d0c827d2
Create Date: 2025-08-20 14:48:04.078434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad7254baf97'
down_revision = '5473d0c827d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True)
        )

    op.execute('UPDATE todo SET completed = False WHERE completed IS NULL;')

    op.alter_column('todo', 'completed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
